# Database Settings
DATBASE_URL: cowin_app.db


# API Settings
API_URL: https://cowin.gov.in/api/v2/appointment/sessions/public/calendarByDistrict
VACCINE_AVAILABILITY_DATE: 0 # default: 0, format:dd-mm-yyyy
DISTRICTS: {Mumbai: 395}


# Toggle Alerts by age
GET_ALERTS_18: true
GET_ALERTS_45: true
# Email Settings
SMTP_HOST: smtp.gmail.com
EMAIL_FROM: from@gmail.com
EMAIL_TO: ['to1@gmail.com', 'to2@gmail.com', 'to3@gmail.com']
EMAIL_SUBJECT: "**IMPORTANT** Vaccine Is Available"
EMAIL_USER_NAME: from@gmail.com
EMAIL_PASSWORD: enteryourpassword

#if you have 2 factor authentication enabaled go to the site below and follow the procedure
#https://support.google.com/accounts/answer/185833?hl=en



